import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

const supabase = createClient(supabaseUrl, supabaseServiceKey)

const SEED_REPORTS = [
  {
    reporter_clerk_id: 'seed_user_1',
    reporter_name: 'Arben Krasniqi',
    title: 'Gropë e madhe në rrugë',
    description: 'Ka një gropë shumë të madhe në rrugën kryesore të lagjes që rrezikon automjetet dhe çiklistët. Gjerësia rreth 80cm dhe thellësia 20cm.',
    category: 'rruge_deme',
    latitude: 42.6629,
    longitude: 21.1655,
    address_text: 'Rr. Garibaldi, Prishtinë',
    municipality: 'Prishtinë',
    status: 'raportuar',
    upvotes: 12,
    views: 45,
  },
  {
    reporter_clerk_id: 'seed_user_2',
    reporter_name: 'Blerina Hoxha',
    title: 'Ndriçim i prishur në Ulpianë',
    description: 'Pesë shtyllë të ndriçimit rrugor janë të fikura në lagjen Ulpianë, rruga Agim Ramadani. Situata është e rrezikshme gjatë natës.',
    category: 'ndricim',
    latitude: 42.6511,
    longitude: 21.1589,
    address_text: 'Rr. Agim Ramadani, Ulpianë, Prishtinë',
    municipality: 'Prishtinë',
    status: 'zgjidhur',
    upvotes: 28,
    views: 112,
    resolved_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    reporter_clerk_id: 'seed_user_3',
    reporter_name: 'Driton Berisha',
    title: 'Mbeturina ilegale afër parkut',
    description: 'Dikush ka hedhur mbeturina të mëdha ilegalisht pranë parkut të lagjes Qyteza Pejton. Ka dyshek, mobilje të vjetruara dhe qese plastike.',
    category: 'mbeturina',
    latitude: 42.2139,
    longitude: 20.7397,
    address_text: 'Afër Parkut Qendror, Prizren',
    municipality: 'Prizren',
    status: 'ne_proces',
    upvotes: 19,
    views: 67,
  },
  {
    reporter_clerk_id: 'seed_user_4',
    reporter_name: 'Fatmire Osmani',
    title: 'Trotuari i bllokuar nga vetura',
    description: 'Vetura të shumta janë parkuar mbi trotuar duke e bllokuar plotësisht kalimin për këmbësorët, duke i detyruar ata të ecin në rrugë.',
    category: 'trotuare',
    latitude: 42.6636,
    longitude: 21.1658,
    address_text: 'Rr. UÇK, Prishtinë',
    municipality: 'Prishtinë',
    status: 'shqyrtim',
    upvotes: 7,
    views: 34,
  },
  {
    reporter_clerk_id: 'seed_user_5',
    reporter_name: 'Gzim Aliu',
    title: 'Rrjedhje uji nga tubi kryesor',
    description: 'Ka rrjedhje të madhe uji nga tubi kryesor i ujësjellësit në rrugën Nënë Tereza. Uji po derdhet gjatë gjithë ditës duke shkaktuar dëme.',
    category: 'uji_kanalizimi',
    latitude: 42.6603,
    longitude: 21.1623,
    address_text: 'Rr. Nënë Tereza, Prishtinë',
    municipality: 'Prishtinë',
    status: 'ne_proces',
    upvotes: 15,
    views: 89,
  },
  {
    reporter_clerk_id: 'seed_user_6',
    reporter_name: 'Hajrie Kelmendi',
    title: 'Ndërtim ilegal pa leje',
    description: 'Është duke u ndërtuar një objekt privat pa leje ndërtimi në lagjen Dardania. Puna është duke vazhduar çdo ditë pavarësisht njoftimeve.',
    category: 'ndertim_ilegal',
    latitude: 42.6528,
    longitude: 21.1612,
    address_text: 'Rr. Dardania, Prishtinë',
    municipality: 'Prishtinë',
    status: 'raportuar',
    upvotes: 22,
    views: 78,
  },
  {
    reporter_clerk_id: 'seed_user_7',
    reporter_name: 'Ilir Mustafa',
    title: 'Parkim ilegal para shkollës',
    description: 'Vetura po parkojnë ilegalisht para hyrjes kryesore të shkollës fillore duke bllokuar kalimin e nxënësve çdo mëngjes dhe çdo pasdite.',
    category: 'parkimi',
    latitude: 42.6618,
    longitude: 21.1641,
    address_text: 'Shkolla Fillore Faik Konica, Prishtinë',
    municipality: 'Prishtinë',
    status: 'raportuar',
    upvotes: 31,
    views: 143,
  },
  {
    reporter_clerk_id: 'seed_user_8',
    reporter_name: 'Jehona Beqiri',
    title: 'Pemë e rrezikshme pranë shtëpive',
    description: 'Një pemë e vjetër dhe e kalbur po rrezikon të bjerë mbi shtëpitë pranë. Degët e mëdha janë duke u thyer gjatë stuhive.',
    category: 'pemve_parqe',
    latitude: 42.3719,
    longitude: 20.4302,
    address_text: 'Lagja e Vjetër, Pejë',
    municipality: 'Pejë',
    status: 'zgjidhur',
    upvotes: 9,
    views: 52,
    resolved_at: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    reporter_clerk_id: 'seed_user_1',
    reporter_name: 'Arben Krasniqi',
    title: 'Asfalti i dëmtuar pas shirave',
    description: 'Pas shirave të fundit, asfalti i rrugës në qendër të lagjes është dëmtuar seriozisht. Ka shumë çarje dhe gropa të vogla por të shumta.',
    category: 'rruge_deme',
    latitude: 42.3642,
    longitude: 20.4281,
    address_text: 'Rruga Kryesore, Pejë',
    municipality: 'Pejë',
    status: 'shqyrtim',
    upvotes: 5,
    views: 28,
  },
  {
    reporter_clerk_id: 'seed_user_9',
    reporter_name: 'Kujtim Haliti',
    title: 'Gropa e rrezikshme pranë shkollës',
    description: 'Gropa e thellë është hapur në trotuar pikërisht pranë shkollës duke rrezikuar nxënësit. Nuk ka shenjëzim apo mbrojtje.',
    category: 'rruge_deme',
    latitude: 42.0728,
    longitude: 21.3333,
    address_text: 'Rr. Lidhja e Prizrenit, Ferizaj',
    municipality: 'Ferizaj',
    status: 'raportuar',
    upvotes: 41,
    views: 198,
  },
  {
    reporter_clerk_id: 'seed_user_10',
    reporter_name: 'Lirije Tahiri',
    title: 'Kanalizimi i bllokuar në lagje',
    description: 'Sistemi i kanalizimit është bllokuar dhe uji i ndotur po derdhet mbi rrugë. Situata është higjienisht e rrezikshme për banorët.',
    category: 'uji_kanalizimi',
    latitude: 42.4627,
    longitude: 21.4694,
    address_text: 'Lagja Arbëria, Gjilan',
    municipality: 'Gjilan',
    status: 'ne_proces',
    upvotes: 16,
    views: 71,
  },
  {
    reporter_clerk_id: 'seed_user_2',
    reporter_name: 'Blerina Hoxha',
    title: 'Çikla e thyer në park',
    description: 'Shumica e mjeteve të lojës në parkun e fëmijëve janë të thyera dhe të rrezikshme. Kjo situatë po i dëmton fëmijët gjatë lojës.',
    category: 'pemve_parqe',
    latitude: 42.2195,
    longitude: 20.7421,
    address_text: 'Parku i Fëmijëve, Prizren',
    municipality: 'Prizren',
    status: 'shqyrtim',
    upvotes: 33,
    views: 156,
  },
  {
    reporter_clerk_id: 'seed_user_3',
    reporter_name: 'Driton Berisha',
    title: 'Shtyllë elektrike e rrezikshme',
    description: 'Shtyllë elektrike e vjetër ka rënë gjysmë dhe kabllot janë të ekspozuara. Rreziku elektrik është i lartë veçanërisht për fëmijët.',
    category: 'ndricim',
    latitude: 42.5592,
    longitude: 20.6892,
    address_text: 'Rr. Fehmi Agani, Gjakovë',
    municipality: 'Gjakovë',
    status: 'raportuar',
    upvotes: 48,
    views: 234,
  },
  {
    reporter_clerk_id: 'seed_user_5',
    reporter_name: 'Gzim Aliu',
    title: 'Mbeturina industriale të hedhura ilegalisht',
    description: 'Dikush ka hedhur mbeturina industriale shumë afër lumit. Rreziku mjedisor është i madh. Ka tonë lëndë kimike dhe plastike.',
    category: 'mbeturina',
    latitude: 42.8738,
    longitude: 20.8659,
    address_text: 'Afër Lumit Sitnica, Mitrovicë',
    municipality: 'Mitrovicë',
    status: 'raportuar',
    upvotes: 27,
    views: 103,
  },
  {
    reporter_clerk_id: 'seed_user_4',
    reporter_name: 'Fatmire Osmani',
    title: 'Trotuar i dëmtuar plotësisht',
    description: 'Trotuar thuajse i shkatërruar plotësisht, me pllaka betoni të thyera dhe gropa. Është i pakalueshëm veçanërisht për persona me aftësi të kufizuara.',
    category: 'trotuare',
    latitude: 42.3699,
    longitude: 20.4315,
    address_text: 'Blloku i Ri, Pejë',
    municipality: 'Pejë',
    status: 'zgjidhur',
    upvotes: 14,
    views: 63,
    resolved_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    reporter_clerk_id: 'seed_user_6',
    reporter_name: 'Hajrie Kelmendi',
    title: 'Semafor i prishur në kryqëzim',
    description: 'Semafori kryesor në kryqëzimin e qendrës nuk funksionon prej 3 ditësh. Ka kaos në trafik dhe aksidente potenciale.',
    category: 'ndricim',
    latitude: 42.6624,
    longitude: 21.1671,
    address_text: 'Sheshi Skënderbej, Prishtinë',
    municipality: 'Prishtinë',
    status: 'ne_proces',
    upvotes: 89,
    views: 412,
  },
  {
    reporter_clerk_id: 'seed_user_7',
    reporter_name: 'Ilir Mustafa',
    title: 'Ndërtesë e braktisur e rrezikshme',
    description: 'Ndërtesë e braktisur dhe e papërfunduar po rrezikohet të shembet. Materialet po bien nga kati i dytë duke rrezikuar kalimtarët.',
    category: 'ndertim_ilegal',
    latitude: 42.3624,
    longitude: 20.4312,
    address_text: 'Rruga e Dëshmorëve, Prizren',
    municipality: 'Prizren',
    status: 'shqyrtim',
    upvotes: 21,
    views: 95,
  },
  {
    reporter_clerk_id: 'seed_user_8',
    reporter_name: 'Jehona Beqiri',
    title: 'Rruga bllokuar nga uji i shirave',
    description: 'Rruga kryesore bllokohet plotësisht pas çdo shiu të fortë. Kanalet e ujrave atmosferikë nuk funksionojnë.',
    category: 'rruge_deme',
    latitude: 42.4635,
    longitude: 21.4701,
    address_text: 'Rr. Ismail Qemali, Gjilan',
    municipality: 'Gjilan',
    status: 'raportuar',
    upvotes: 18,
    views: 74,
  },
  {
    reporter_clerk_id: 'seed_user_9',
    reporter_name: 'Kujtim Haliti',
    title: 'Mbetje ndërtimi bllokojnë rrugën',
    description: 'Materialet e ndërtimit janë hedhur mbi rrugën publike duke e bllokuar pjesërisht. Kamionët nuk mund të kalojnë.',
    category: 'tjeter',
    latitude: 42.0715,
    longitude: 21.3301,
    address_text: 'Rr. Skënderbeu, Ferizaj',
    municipality: 'Ferizaj',
    status: 'raportuar',
    upvotes: 6,
    views: 29,
  },
  {
    reporter_clerk_id: 'seed_user_10',
    reporter_name: 'Lirije Tahiri',
    title: 'Parkim mbi bari publik',
    description: 'Vetura po parkojnë sistematikisht mbi barin publik të sheshit duke shkatërruar hapësirën e gjelbër.',
    category: 'parkimi',
    latitude: 42.8744,
    longitude: 20.8672,
    address_text: 'Sheshi Qendror, Mitrovicë',
    municipality: 'Mitrovicë',
    status: 'zgjidhur',
    upvotes: 11,
    views: 48,
    resolved_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    reporter_clerk_id: 'seed_user_1',
    reporter_name: 'Arben Krasniqi',
    title: 'Gropa me ujë stagnant rrezikon shëndetin',
    description: 'Gropa e madhe me ujë stagnant pranë kopshtit të fëmijëve. Rreziku nga insektet dhe sëmundjet është i lartë.',
    category: 'uji_kanalizimi',
    latitude: 42.5589,
    longitude: 20.6879,
    address_text: 'Lagja Çabrati, Gjakovë',
    municipality: 'Gjakovë',
    status: 'shqyrtim',
    upvotes: 25,
    views: 116,
  },
  {
    reporter_clerk_id: 'seed_user_3',
    reporter_name: 'Driton Berisha',
    title: 'Shkallët publike të thyera',
    description: 'Shkallët në hyrje të parkut qendror janë të thyera dhe të rrezikshme. Disa persona janë plagosur tashmë.',
    category: 'trotuare',
    latitude: 42.0731,
    longitude: 21.3342,
    address_text: 'Parku Qendror, Ferizaj',
    municipality: 'Ferizaj',
    status: 'ne_proces',
    upvotes: 37,
    views: 167,
  },
  {
    reporter_clerk_id: 'seed_user_5',
    reporter_name: 'Gzim Aliu',
    title: 'Druri i rënë mbi rrugë',
    description: 'Pas stuhisë, një dru i madh ka rënë mbi rrugën kryesore dhe e bllokon plotësisht. Nevoja urgjente për heqje.',
    category: 'pemve_parqe',
    latitude: 42.4619,
    longitude: 21.4682,
    address_text: 'Bulevardit Kryesor, Gjilan',
    municipality: 'Gjilan',
    status: 'refuzuar',
    upvotes: 3,
    views: 19,
  },
  {
    reporter_clerk_id: 'seed_user_2',
    reporter_name: 'Blerina Hoxha',
    title: 'Probleme me furnizimin me ujë',
    description: 'Furnizimi me ujë ka ndërprerje të shpeshta pa paralajmërim. Banorët e lagjes ankohen prej javësh pa zgjidhje.',
    category: 'uji_kanalizimi',
    latitude: 42.2148,
    longitude: 20.7408,
    address_text: 'Lagja Remzi Ademi, Prizren',
    municipality: 'Prizren',
    status: 'raportuar',
    upvotes: 44,
    views: 201,
  },
]

async function seed() {
  console.log('🌱 Duke filluar seed...')

  const { error } = await supabase.from('reports').insert(SEED_REPORTS)

  if (error) {
    console.error('❌ Gabim gjatë seed:', error.message)
    process.exit(1)
  }

  console.log(`✅ U shtuan ${SEED_REPORTS.length} raporte me sukses!`)
  process.exit(0)
}

seed()
